version: '3.9'
services:
  db:
    image: postgres:15
    container_name: football-db
    environment:
      POSTGRES_USER: football_user
      POSTGRES_PASSWORD: football_pw
      POSTGRES_DB: football_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - football-net

  api:
    build: .
    container_name: football-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/football_db
      SPRING_DATASOURCE_USERNAME: football_user
      SPRING_DATASOURCE_PASSWORD: football_pw
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - football-net

volumes:
  db-data:

networks:
  football-net:
    driver: bridge