spring:
  application:
    name: football

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

cors:
  allowed-origins:
    - http://localhost:5173
    - https://football-app-4fa6e.web.app
    - http://football-frontend.onrender.com

  bootstrap:
    nation:
      enabled: true
    team:
      enabled: true
    player:
      enabled: true
